### ISSUE TITLE
Not supported for progma solidity >=0.4.22 <0.6.2;

### ISSUE THREAD

**Issue by denismp** [Arachnid/solidity-stringutils#41]
Source "github.com/Arachnid/solidity-stringutils/strings.sol" not found: File import callback not supported

pragma solidity >=0.4.22 <0.6.2;
import "github.com/Arachnid/solidity-stringutils/strings.sol"

**Comment by Arachnid** [comment]
I'm sorry, I don't understand the nature of the problem. Can you elaborate?

**Comment by denismp** [comment]
I tried to import your library, but I got the "File import callback not supported"  You can see the pragma solidity that I am attempting to use for the compiler, which is set to 0.6.1.
