### ISSUE TITLE
Issue appeared in remix

### ISSUE THREAD

**Issue by terryjiang2020** [Arachnid/solidity-stringutils#55]
Warning: This declaration shadows an existing declaration.
--> .deps/github/Arachnid/solidity-stringutils/src/strings.sol:46:42:
|
46 | function memcpy(uint dest, uint src, uint len) private pure {
| ^^^^^^^^
Note: The shadowed declaration is here:
--> .deps/github/Arachnid/solidity-stringutils/src/strings.sol:86:5:
|
86 | function len(bytes32 self) internal pure returns (uint) {
| ^ (Relevant source part starts here and spans across multiple lines).
Note: The shadowed declaration is here:
--> .deps/github/Arachnid/solidity-stringutils/src/strings.sol:161:5:
|
161 | function len(slice memory self) internal pure returns (uint l) {
| ^ (Relevant source part starts here and spans across multiple lines).

Looks like the issue is completely inside this repo?

Solidity 0.8 btw.

**Comment by Arachnid** [comment]
These are warnings, not errors. You can safely ignore them.
